# MNI coordinates for vertices

import os
import mne
import numpy as np
import pandas as pd
from scipy import stats
from statsmodels.stats import multitest as mul


In [33]:
os.environ["SUBJECTS_DIR"] = "/home/vtretyakova/Рабочий стол/speach_learn/Labels/freesurfer"
subjects_dir = "/home/vtretyakova/Рабочий стол/speach_learn/Labels/freesurfer"
subject = "avg_platon_27sub"

In [3]:
# Читаем лейблы (они должны лежать в той директории, которую мы указали, т.е. во 
#/home/vtretyakova/Рабочий стол/speach_learn/Labels/freesurfer/avg_platon_27sub/label)

labels = mne.read_labels_from_annot('avg_platon_27sub', 'aparc.a2009s')

Reading labels from parcellation...
   read 75 labels from /home/vtretyakova/Рабочий стол/speach_learn/Labels/freesurfer/avg_platon_27sub/label/lh.aparc.a2009s.annot
   read 75 labels from /home/vtretyakova/Рабочий стол/speach_learn/Labels/freesurfer/avg_platon_27sub/label/rh.aparc.a2009s.annot


In [4]:
chosen_labels_name = [
    'G_and_S_cingul-Mid-Ant-lh',
    'G_cingul-Post-ventral-lh',
    'G_oc-temp_med-Parahip-lh',
    'S_front_inf-lh',
    'S_front_sup-lh'
]

In [5]:
chosen_labels = [label for label in labels if label.name in chosen_labels_name]
chosen_labels

[<Label | avg_platon_27sub, 'G_and_S_cingul-Mid-Ant-lh', lh : 1942 vertices>,
 <Label | avg_platon_27sub, 'G_cingul-Post-ventral-lh', lh : 575 vertices>,
 <Label | avg_platon_27sub, 'G_oc-temp_med-Parahip-lh', lh : 2288 vertices>,
 <Label | avg_platon_27sub, 'S_front_inf-lh', lh : 2273 vertices>,
 <Label | avg_platon_27sub, 'S_front_sup-lh', lh : 3100 vertices>]

# Download p_value average data (three time points - PreM, M, PostM)

In [6]:
stc = mne.read_source_estimate('/net/server/data/home/inside/Niherus_work_transfer/Make_source_for_beta/MAIN_SCRIPT/Source/SourceEstimate/beta_reactclean_15_26/p_val/p-val_full_fdr_r2-end_sub22_interv_merged-lh.stc')
stc.subject = "avg_platon_27sub"

# We need only Movements interval, so doenload donor for one point

In [7]:
donor = mne.read_source_estimate('/net/server/data/home/inside/Niherus_work_transfer/Make_source_for_beta/MAIN_SCRIPT/Source/SourceEstimate/beta_reactclean_15_26/p_val_fdr/p-val_no_fdr_r1-st_vs_r2-end_sub22_0.1-0.55_merged')
donor.subject = "avg_platon_27sub"
donor

<SourceEstimate | 20484 vertices, subject : avg_platon_27sub, tmin : 100.0 (ms), tmax : 100.0 (ms), tstep : 50.0 (ms), data shape : (20484, 1), ~240 kB>

In [8]:
stc_M_active2 = []
for i in range(len(stc.data)):
    s = stc.data[i][1]
    stc_M_active2.append(s)
    
print(len(stc_M_active2))

stc_M_active2 = np.array(stc_M_active2)
stc_M_active2 = stc_M_active2[:, np.newaxis]
print(stc_M_active2.shape) 
donor.data = stc_M_active2

20484
(20484, 1)


In [9]:
stc_in_label_0 = donor.in_label(chosen_labels[0])
stc_in_label_0

<SourceEstimate | 125 vertices, subject : avg_platon_27sub, tmin : 100.0 (ms), tmax : 100.0 (ms), tstep : 50.0 (ms), data shape : (125, 1), ~2 kB>

# Data from stc

In [13]:
stc_in_label_0_data = stc_in_label_0.data
stc_in_label_0_data.shape

(125, 1)

In [14]:
stc_in_label_0_data

array([[0.9907663 ],
       [0.94816035],
       [0.991758  ],
       [0.99204004],
       [0.99735826],
       [0.93570316],
       [0.9952798 ],
       [0.99763346],
       [0.9953461 ],
       [0.9826458 ],
       [0.9964803 ],
       [0.9949557 ],
       [0.9951283 ],
       [0.99411577],
       [0.99886805],
       [0.99947995],
       [0.996921  ],
       [0.987853  ],
       [0.9936928 ],
       [0.98939025],
       [0.9536147 ],
       [0.99724233],
       [0.9977853 ],
       [0.9984481 ],
       [0.99650073],
       [0.99517757],
       [0.9912292 ],
       [0.99054205],
       [0.9858867 ],
       [0.9807239 ],
       [0.94733983],
       [0.9944036 ],
       [0.9921971 ],
       [0.9932392 ],
       [0.99502695],
       [0.99894845],
       [0.99761504],
       [0.9989701 ],
       [0.99481225],
       [0.9790599 ],
       [0.9926553 ],
       [0.9887038 ],
       [0.9882566 ],
       [0.99420196],
       [0.99458987],
       [0.99489325],
       [0.997766  ],
       [0.992

In [15]:
stc_in_label_0_data_reshape = np.reshape(stc_in_label_0_data, (125,))
stc_in_label_0_data_reshape

array([0.9907663 , 0.94816035, 0.991758  , 0.99204004, 0.99735826,
       0.93570316, 0.9952798 , 0.99763346, 0.9953461 , 0.9826458 ,
       0.9964803 , 0.9949557 , 0.9951283 , 0.99411577, 0.99886805,
       0.99947995, 0.996921  , 0.987853  , 0.9936928 , 0.98939025,
       0.9536147 , 0.99724233, 0.9977853 , 0.9984481 , 0.99650073,
       0.99517757, 0.9912292 , 0.99054205, 0.9858867 , 0.9807239 ,
       0.94733983, 0.9944036 , 0.9921971 , 0.9932392 , 0.99502695,
       0.99894845, 0.99761504, 0.9989701 , 0.99481225, 0.9790599 ,
       0.9926553 , 0.9887038 , 0.9882566 , 0.99420196, 0.99458987,
       0.99489325, 0.997766  , 0.9927966 , 0.99497175, 0.9979151 ,
       0.99565876, 0.9976909 , 0.9990939 , 0.9911458 , 0.9948165 ,
       0.9958067 , 0.9932787 , 0.99546766, 0.99575216, 0.99578935,
       0.9900326 , 0.987295  , 0.9916765 , 0.9915217 , 0.99389106,
       0.9811471 , 0.9425865 , 0.9375378 , 0.96900487, 0.9528483 ,
       0.9975495 , 0.9966254 , 0.99536115, 0.9937504 , 0.99915

In [37]:
stc_in_label_0_data_reshape_sorted = -np.sort(-stc_in_label_0_data_reshape)
stc_in_label_0_data_reshape_sorted[:10]

array([0.9997508 , 0.999727  , 0.99959314, 0.99947995, 0.9992302 ,
       0.9991552 , 0.9990939 , 0.9989701 , 0.99894845, 0.99890244],
      dtype=float32)

In [38]:
stc_in_label_0_data_reshape_sorted_arg = np.argsort(-stc_in_label_0_data_reshape)
stc_in_label_0_data_reshape_sorted_arg[:10]



array([ 77,  76,  75,  15, 103,  74,  52,  37,  35, 107])

# common indexes for vertices in label

In [11]:
stc_in_label_0.vertices[0]

array([  74,  111,  115,  253,  422,  501,  506,  509,  510,  511,  944,
        945,  946, 1116, 1117, 1118, 1119, 1120, 1121, 1122, 1123, 1607,
       2170, 2171, 2172, 2173, 2174, 2175, 2176, 2177, 2178, 2864, 2865,
       2866, 3035, 3036, 3037, 3038, 3039, 3040, 3041, 3042, 3638, 4274,
       4276, 4278, 4788, 4789, 4790, 4791, 4792, 4793, 4794, 4795, 4796,
       4797, 4798, 4799, 4800, 4801, 4802, 4803, 4804, 4805, 4806, 4807,
       4808, 4809, 4810, 4811, 6308, 6309, 6310, 6311, 6618, 6619, 6620,
       6621, 6622, 6623, 6624, 6625, 6626, 6627, 6628, 6629, 6630, 6631,
       6632, 7588, 7589, 7590, 7591, 7596, 7597, 7598, 8443, 9014, 9015,
       9071, 9073, 9074, 9075, 9076, 9078, 9079, 9080, 9081, 9082, 9083,
       9084, 9085, 9086, 9087, 9088, 9089, 9090, 9091, 9092, 9093, 9094,
       9095, 9096, 9098, 9099])

In [30]:
len(stc_in_label_0.vertices[0])

125

In [31]:
stc_in_label_0.vertices[0][14]

1117

# common indexes for 10 vertices with max p_value 

In [39]:
vertices_max_list = stc_in_label_0_data_reshape_sorted_arg[:10].tolist()
vertices_max_list

[77, 76, 75, 15, 103, 74, 52, 37, 35, 107]

In [40]:
common_indexes_max = []
for ind in vertices_max_list:
    common_indexes_max.append(stc_in_label_0.vertices[0][ind])
    
common_indexes_max    

[6621, 6620, 6619, 1118, 9076, 6618, 4794, 3038, 3036, 9081]

In [41]:
common_indexes_max = np.array(common_indexes_max)
common_indexes_max

array([6621, 6620, 6619, 1118, 9076, 6618, 4794, 3038, 3036, 9081])

# Vertices to MNI coordinate

https://mne.tools/stable/generated/mne.vertex_to_mni.html  

https://mne.tools/stable/auto_examples/inverse/label_activation_from_stc.html#sphx-glr-auto-examples-inverse-label-activation-from-stc-py

In [42]:
mni_0_lh = mne.vertex_to_mni(common_indexes_max, 0, 'avg_platon_27sub', subjects_dir=subjects_dir)
mni_0_lh

array([[-11.12793636,  18.33568176,  27.38112452],
       [ -8.54681301,  18.43683991,  27.0002518 ],
       [-10.09684849,  20.42596612,  25.58917049],
       [ -9.63332748,  16.24067863,  28.76573184],
       [ -5.77932072,  19.92279995,  20.82356837],
       [-11.35647774,  23.12825762,  24.55611995],
       [ -6.49138069,  18.54348931,  26.56808284],
       [-12.38323498,  19.18790038,  29.16841701],
       [-12.4078455 ,  24.31703553,  26.60349087],
       [ -7.4679389 ,  16.57853492,  28.33433726]])